services:
  - type: web
    name: careercoded-blog
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run deploy:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: /api
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ADMIN_NAME
        value: CareerCoded Admin
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
